In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.rand(3, 4, 5).type(torch.float32)
x.type(), x

('torch.FloatTensor',
 tensor([[[0.5106, 0.6484, 0.5123, 0.5823, 0.7242],
          [0.5913, 0.4826, 0.4921, 0.4019, 0.6926],
          [0.2064, 0.1134, 0.1811, 0.5040, 0.3958],
          [0.1522, 0.4380, 0.4583, 0.8719, 0.2302]],
 
         [[0.3952, 0.8780, 0.9117, 0.3573, 0.9847],
          [0.5619, 0.7531, 0.9910, 0.0544, 0.0456],
          [0.9372, 0.6297, 0.9792, 0.3397, 0.8028],
          [0.1934, 0.2093, 0.5388, 0.1627, 0.7246]],
 
         [[0.3642, 0.7625, 0.6654, 0.5385, 0.7845],
          [0.8326, 0.2648, 0.9314, 0.6927, 0.2298],
          [0.7027, 0.8443, 0.9355, 0.8404, 0.5842],
          [0.1747, 0.4476, 0.0140, 0.4312, 0.1219]]]))

In [3]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
x_resized = torch.reshape(x, (6, 10))
x_resized.shape, x_resized

(torch.Size([6, 10]),
 tensor([[0.5106, 0.6484, 0.5123, 0.5823, 0.7242, 0.5913, 0.4826, 0.4921, 0.4019,
          0.6926],
         [0.2064, 0.1134, 0.1811, 0.5040, 0.3958, 0.1522, 0.4380, 0.4583, 0.8719,
          0.2302],
         [0.3952, 0.8780, 0.9117, 0.3573, 0.9847, 0.5619, 0.7531, 0.9910, 0.0544,
          0.0456],
         [0.9372, 0.6297, 0.9792, 0.3397, 0.8028, 0.1934, 0.2093, 0.5388, 0.1627,
          0.7246],
         [0.3642, 0.7625, 0.6654, 0.5385, 0.7845, 0.8326, 0.2648, 0.9314, 0.6927,
          0.2298],
         [0.7027, 0.8443, 0.9355, 0.8404, 0.5842, 0.1747, 0.4476, 0.0140, 0.4312,
          0.1219]]))

In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
a = torch.FloatTensor([1, 4, 2, 2, 1])
x_mul = torch.mul(x, a)
x_mul

tensor([[[0.5106, 2.5937, 1.0247, 1.1647, 0.7242],
         [0.5913, 1.9305, 0.9843, 0.8038, 0.6926],
         [0.2064, 0.4537, 0.3622, 1.0079, 0.3958],
         [0.1522, 1.7519, 0.9166, 1.7439, 0.2302]],

        [[0.3952, 3.5121, 1.8234, 0.7146, 0.9847],
         [0.5619, 3.0124, 1.9820, 0.1087, 0.0456],
         [0.9372, 2.5188, 1.9583, 0.6794, 0.8028],
         [0.1934, 0.8373, 1.0776, 0.3254, 0.7246]],

        [[0.3642, 3.0501, 1.3308, 1.0770, 0.7845],
         [0.8326, 1.0590, 1.8627, 1.3854, 0.2298],
         [0.7027, 3.3772, 1.8710, 1.6807, 0.5842],
         [0.1747, 1.7902, 0.0280, 0.8624, 0.1219]]])

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
y = torch.matmul(x_resized, torch.transpose(x_resized, 0, 1))
y.shape, y

(torch.Size([6, 6]),
 tensor([[3.2732, 1.8886, 3.3963, 3.2155, 3.4192, 2.8820],
         [1.8886, 1.7372, 1.8435, 1.6078, 2.1905, 1.6980],
         [3.3963, 1.8435, 4.7257, 3.5700, 4.0234, 3.2256],
         [3.2155, 1.6078, 3.5700, 3.9166, 3.2833, 3.1543],
         [3.4192, 2.1905, 4.0234, 3.2833, 4.2258, 3.0369],
         [2.8820, 1.6980, 3.2256, 3.1543, 3.0369, 3.5612]]))

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

x = Variable(torch.FloatTensor([1.]), requires_grad = True)
z = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = Variable(torch.FloatTensor([2.]), requires_grad = True)

y = x**3 + z - 75 * t
y

tensor([-148.5000], grad_fn=<SubBackward0>)

In [8]:
y.backward([x, z, t])
x.grad, z.grad, t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [9]:
torch.stack([x.grad, z.grad, t.grad]).sum()

tensor(-71.)

In [10]:
# Создайте единичный тензор размера 5x6
x_one = torch.ones(5, 6)
x_one

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [11]:
# Переведите его в формат numpy
import numpy as np
np.array(x_one)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [12]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

In [13]:
from torch import nn 
from torch import optim

In [14]:
w1 =  Variable(torch.randn(1), requires_grad = True)

optimizer = torch.optim.Adam([w1], lr=0.001)
criterion = nn.MSELoss()

x = Variable(torch.randn(1), requires_grad = True)
y = Variable(torch.randn(1), requires_grad = False)

w1, x, y

(tensor([-0.5995], requires_grad=True),
 tensor([1.1942], requires_grad=True),
 tensor([0.4223]))

In [15]:
optimizer.zero_grad()
pred = x**w1 - 2 * x**2 + 5
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  6.889292240142822


In [16]:
loss.backward()
loss

tensor(6.8893, grad_fn=<MseLossBackward>)

In [17]:
optimizer.step()
w1

tensor([-0.6005], requires_grad=True)